version: '3.9'
services:
  car-shop:
    build: reverse-proxy
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      target: builder
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_HOST=backend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      interval: 3s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      interval: 3s
      timeout: 10s
      retries: 5

  db:
    image: docker.io/healthcheck/mongo
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5
