version: '3.9'
services:
  reverse-proxy:
    image: docker.io/j0n4t/car-shop-reverse-proxy
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: always

  frontend:
    image: docker.io/j0n4t/car-shop-frontend
    ports:
      - 80
    environment:
      - BACKEND_HOST=backend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      interval: 3s
      timeout: 10s
      retries: 5

  backend:
    image: docker.io/j0n4t/car-shop-backend
    ports:
      - 8080
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      interval: 3s
      timeout: 10s
      retries: 5

  db:
    image: docker.io/mongo
    ports:
      - 27017
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 3s
      timeout: 10s
      retries: 5
